import { Head, router, useForm, usePage } from '@inertiajs/react';
import AdminLayout from '@/Layouts/AdminLayout';
import { useState } from 'react';
import { DocumentArrowDownIcon, PlusIcon, TrashIcon, XMarkIcon } from '@heroicons/react/24/outline';

const REPORT_TYPES = [
    { value: 'student_health',  label: 'Student Health' },
    { value: 'faculty_health',  label: 'Faculty Health' },
    { value: 'appointment',     label: 'Appointment' },
    { value: 'medicine',        label: 'Medicine' },
    { value: 'pregnancy',       label: 'Pregnancy' },
    { value: 'survey',          label: 'Survey' },
];

const STATUS_STYLES = {
    pending:    'badge-yellow',
    processing: 'badge-blue',
    completed:  'badge-green',
    failed:     'badge-red',
};

export default function Reports({ reports }) {
    const { auth } = usePage().props;
    const isSuperAdmin = auth.user?.role?.name === 'super_admin';

    const [showForm, setShowForm] = useState(false);
    const [deletingId, setDeletingId] = useState(null);

    const { data, setData, post, processing, errors, reset } = useForm({
        type: 'student_health',
        title: '',
        format: 'pdf',
        filters: {},
    });

    const submit = (e) => {
        e.preventDefault();
        post(route('admin.reports.store'), {
            onSuccess: () => { setShowForm(false); reset(); },
        });
    };

    const handleDelete = (id) => {
        if (!confirm('Are you sure you want to delete this report? This cannot be undone.')) return;
        setDeletingId(id);
        router.delete(route('admin.reports.destroy', id), {
            preserveScroll: true,
            onFinish: () => setDeletingId(null),
        });
    };

    const closeForm = () => { setShowForm(false); reset(); };

    return (
        <AdminLayout title="Reports">
            <Head title="Reports" />

            {/* ── Page header ── */}
            <div className="page-header">
                <div>
                    <h2 className="page-title">Reports</h2>
                    <p className="page-subtitle">Generate and download clinic reports</p>
                </div>
                <button onClick={() => setShowForm(true)} className="btn-primary btn-sm">
                    <PlusIcon className="w-4 h-4 mr-1" />
                    <span>Generate Report</span>
                </button>
            </div>

            {/* ── Desktop table (hidden on small screens) ── */}
            <div className="card hidden md:block">
                <div className="table-wrapper">
                    <table className="table">
                        <thead>
                            <tr>
                                <th>Title</th>
                                <th>Type</th>
                                <th>Format</th>
                                <th>Generated By</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {reports.data.map(r => (
                                <tr key={r.id}>
                                    <td className="font-medium">{r.title}</td>
                                    <td>
                                        <span className="text-xs font-mono bg-gray-100 px-2 py-0.5 rounded">
                                            {r.type}
                                        </span>
                                    </td>
                                    <td>
                                        <span className="badge badge-gray uppercase text-xs">{r.format}</span>
                                    </td>
                                    <td className="text-gray-500 text-sm">{r.generated_by?.name}</td>
                                    <td>
                                        <span className={`badge ${STATUS_STYLES[r.status]}`}>{r.status}</span>
                                    </td>
                                    <td>
                                        <div className="flex items-center gap-2">
                                            {r.status === 'completed' && (
                                                <a href={route('admin.reports.download', r.id)} className="btn-secondary btn-sm">
                                                    <DocumentArrowDownIcon className="w-4 h-4 mr-1" />Download
                                                </a>
                                            )}
                                            {isSuperAdmin && (
                                                <button
                                                    onClick={() => handleDelete(r.id)}
                                                    disabled={deletingId === r.id}
                                                    className="btn-danger btn-sm"
                                                >
                                                    <TrashIcon className="w-4 h-4 mr-1" />
                                                    {deletingId === r.id ? 'Deleting…' : 'Delete'}
                                                </button>
                                            )}
                                        </div>
                                    </td>
                                </tr>
                            ))}
                            {!reports.data.length && (
                                <tr>
                                    <td colSpan={6} className="text-center text-gray-400 py-8">
                                        No reports yet.
                                    </td>
                                </tr>
                            )}
                        </tbody>
                    </table>
                </div>
            </div>

            {/* ── Mobile card list (visible only on small screens) ── */}
            <div className="md:hidden space-y-3">
                {reports.data.length === 0 && (
                    <div className="card text-center text-gray-400 py-10">No reports yet.</div>
                )}

                {reports.data.map(r => (
                    <div key={r.id} className="card p-4 space-y-3">
                        {/* Title + status row */}
                        <div className="flex items-start justify-between gap-2">
                            <p className="font-semibold text-gray-800 leading-snug">{r.title}</p>
                            <span className={`badge ${STATUS_STYLES[r.status]} shrink-0`}>{r.status}</span>
                        </div>

                        {/* Meta row */}
                        <div className="flex flex-wrap gap-x-4 gap-y-1 text-sm text-gray-500">
                            <span>
                                <span className="text-xs font-mono bg-gray-100 px-2 py-0.5 rounded">{r.type}</span>
                            </span>
                            <span className="badge badge-gray uppercase text-xs self-center">{r.format}</span>
                            {r.generated_by?.name && (
                                <span className="self-center">by {r.generated_by.name}</span>
                            )}
                        </div>

                        {/* Actions */}
                        {(r.status === 'completed' || isSuperAdmin) && (
                            <div className="flex gap-2 pt-1">
                                {r.status === 'completed' && (
                                    <a
                                        href={route('admin.reports.download', r.id)}
                                        className="btn-secondary btn-sm flex-1 justify-center"
                                    >
                                        <DocumentArrowDownIcon className="w-4 h-4 mr-1" />Download
                                    </a>
                                )}
                                {isSuperAdmin && (
                                    <button
                                        onClick={() => handleDelete(r.id)}
                                        disabled={deletingId === r.id}
                                        className="btn-danger btn-sm flex-1 justify-center"
                                    >
                                        <TrashIcon className="w-4 h-4 mr-1" />
                                        {deletingId === r.id ? 'Deleting…' : 'Delete'}
                                    </button>
                                )}
                            </div>
                        )}
                    </div>
                ))}
            </div>

            {/* ── Generate Report modal ── */}
            {showForm && (
                <div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center bg-black/50 p-0 sm:p-4">
                    {/* Sheet slides up on mobile, centered modal on sm+ */}
                    <div className="bg-white w-full sm:max-w-md sm:rounded-xl rounded-t-2xl shadow-xl">
                        {/* Modal header */}
                        <div className="flex items-center justify-between px-5 pt-5 pb-3 border-b border-gray-100">
                            <h3 className="font-semibold text-gray-800">Generate New Report</h3>
                            <button
                                onClick={closeForm}
                                className="text-gray-400 hover:text-gray-600 p-1 rounded-lg hover:bg-gray-100 transition"
                                aria-label="Close"
                            >
                                <XMarkIcon className="w-5 h-5" />
                            </button>
                        </div>

                        {/* Modal body */}
                        <form onSubmit={submit} className="p-5 space-y-4">
                            <div>
                                <label className="label">Report Type</label>
                                <select
                                    value={data.type}
                                    onChange={e => setData('type', e.target.value)}
                                    className="input"
                                >
                                    {REPORT_TYPES.map(t => (
                                        <option key={t.value} value={t.value}>{t.label}</option>
                                    ))}
                                </select>
                            </div>

                            <div>
                                <label className="label">Title</label>
                                <input
                                    value={data.title}
                                    onChange={e => setData('title', e.target.value)}
                                    className={`input ${errors.title ? 'input-error' : ''}`}
                                    placeholder="e.g. Student Health Report Q1 2025"
                                />
                                {errors.title && <p className="error-msg">{errors.title}</p>}
                            </div>

                            <div>
                                <label className="label">Format</label>
                                <div className="grid grid-cols-2 gap-3 mt-1">
                                    {['pdf', 'excel'].map(f => (
                                        <label
                                            key={f}
                                            className={`flex items-center justify-center gap-2 border rounded-lg py-2.5 cursor-pointer text-sm font-medium uppercase transition
                                                ${data.format === f
                                                    ? 'border-clinic-600 bg-clinic-50 text-clinic-700'
                                                    : 'border-gray-200 text-gray-500 hover:border-gray-300'
                                                }`}
                                        >
                                            <input
                                                type="radio"
                                                value={f}
                                                checked={data.format === f}
                                                onChange={() => setData('format', f)}
                                                className="sr-only"
                                            />
                                            {f}
                                        </label>
                                    ))}
                                </div>
                            </div>

                            {/* Footer buttons */}
                            <div className="flex gap-3 pt-1">
                                <button type="submit" disabled={processing} className="btn-primary flex-1 justify-center">
                                    {processing ? 'Queuing…' : 'Generate'}
                                </button>
                                <button type="button" onClick={closeForm} className="btn-secondary flex-1 justify-center">
                                    Cancel
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            )}
        </AdminLayout>
    );
}
