import { Head, router, useForm, usePage } from '@inertiajs/react';
import AdminLayout from '@/Layouts/AdminLayout';
import { useState } from 'react';
import { DocumentArrowDownIcon, PlusIcon, TrashIcon } from '@heroicons/react/24/outline';

export default function Reports({ reports }) {
    const { auth } = usePage().props;
    const isSuperAdmin = auth.user?.role === 'super_admin';

    const [showForm, setShowForm] = useState(false);
    const [deletingId, setDeletingId] = useState(null);
    const { data, setData, post, processing, errors, reset } = useForm({
        type: 'student_health', title: '', format: 'pdf', filters: {}
    });

    const submit = (e) => {
        e.preventDefault();
        post(route('admin.reports.store'), { onSuccess: () => { setShowForm(false); reset(); } });
    };

    const handleDelete = (id) => {
        if (!confirm('Are you sure you want to delete this report? This cannot be undone.')) return;
        setDeletingId(id);
        router.delete(route('admin.reports.destroy', id), {
            preserveScroll: true,
            onFinish: () => setDeletingId(null),
        });
    };

    const statusBadge = (s) => {
        const map = { pending: 'badge-yellow', processing: 'badge-blue', completed: 'badge-green', failed: 'badge-red' };
        return <span className={`badge ${map[s]}`}>{s}</span>;
    };

    return (
        <AdminLayout title="Reports">
            <Head title="Reports" />
            <div className="page-header">
                <div><h2 className="page-title">Reports</h2><p className="page-subtitle">Generate and download clinic reports</p></div>
                <button onClick={() => setShowForm(true)} className="btn-primary btn-sm">
                    <PlusIcon className="w-4 h-4 mr-1" />Generate Report
                </button>
            </div>
            <div className="card">
                <div className="table-wrapper">
                    <table className="table">
                        <thead>
                            <tr>
                                <th>Title</th><th>Type</th><th>Format</th>
                                <th>Generated By</th><th>Status</th><th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {reports.data.map(r => (
                                <tr key={r.id}>
                                    <td className="font-medium">{r.title}</td>
                                    <td><span className="text-xs font-mono bg-gray-100 px-2 py-0.5 rounded">{r.type}</span></td>
                                    <td><span className="badge badge-gray uppercase text-xs">{r.format}</span></td>
                                    <td className="text-gray-500 text-sm">{r.generated_by?.name}</td>
                                    <td>{statusBadge(r.status)}</td>
                                    <td>
                                        <div className="flex items-center gap-2">
                                            {r.status === 'completed' && (
                                                <a href={route('admin.reports.download', r.id)} className="btn-secondary btn-sm">
                                                    <DocumentArrowDownIcon className="w-4 h-4 mr-1" />Download
                                                </a>
                                            )}
                                            {isSuperAdmin && (
                                                <button
                                                    onClick={() => handleDelete(r.id)}
                                                    disabled={deletingId === r.id}
                                                    className="btn-danger btn-sm"
                                                >
                                                    <TrashIcon className="w-4 h-4 mr-1" />
                                                    {deletingId === r.id ? 'Deleting…' : 'Delete'}
                                                </button>
                                            )}
                                        </div>
                                    </td>
                                </tr>
                            ))}
                            {!reports.data.length && (
                                <tr><td colSpan={6} className="text-center text-gray-400 py-8">No reports yet.</td></tr>
                            )}
                        </tbody>
                    </table>
                </div>
            </div>

            {showForm && (
                <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4">
                    <div className="bg-white rounded-xl shadow-xl p-6 w-full max-w-md">
                        <h3 className="font-semibold mb-4">Generate New Report</h3>
                        <form onSubmit={submit} className="space-y-3">
                            <div>
                                <label className="label">Report Type</label>
                                <select value={data.type} onChange={e => setData('type', e.target.value)} className="input">
                                    {['student_health','faculty_health','appointment','medicine','pregnancy','survey'].map(t => (
                                        <option key={t} value={t}>{t.replace('_', ' ')}</option>
                                    ))}
                                </select>
                            </div>
                            <div>
                                <label className="label">Title</label>
                                <input value={data.title} onChange={e => setData('title', e.target.value)}
                                    className={`input ${errors.title ? 'input-error' : ''}`}
                                    placeholder="e.g. Student Health Report Q1 2025" />
                                {errors.title && <p className="error-msg">{errors.title}</p>}
                            </div>
                            <div>
                                <label className="label">Format</label>
                                <div className="flex gap-4 mt-1">
                                    {['pdf','excel'].map(f => (
                                        <label key={f} className="flex items-center gap-2 cursor-pointer">
                                            <input type="radio" value={f} checked={data.format === f}
                                                onChange={() => setData('format', f)} className="text-clinic-600" />
                                            <span className="text-sm uppercase font-medium">{f}</span>
                                        </label>
                                    ))}
                                </div>
                            </div>
                            <div className="flex gap-3 pt-2">
                                <button type="submit" disabled={processing} className="btn-primary">
                                    {processing ? 'Queuing…' : 'Generate'}
                                </button>
                                <button type="button" onClick={() => setShowForm(false)} className="btn-secondary">Cancel</button>
                            </div>
                        </form>
                    </div>
                </div>
            )}
        </AdminLayout>
    );
}